// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: finance/pkg/proto/finance/finance.proto

package finance

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FinanceServiceClient is the client API for FinanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinanceServiceClient interface {
	Create(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Empty, error)
	GetRecordsForDay(ctx context.Context, in *DateRequest, opts ...grpc.CallOption) (*Records, error)
	ProfitForMonth(ctx context.Context, in *DateRequest, opts ...grpc.CallOption) (*Profit, error)
	GetValuesForMonth(ctx context.Context, in *DateRequest, opts ...grpc.CallOption) (*Values, error)
	GetValuesForYear(ctx context.Context, in *DateRequest, opts ...grpc.CallOption) (*Values, error)
}

type financeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFinanceServiceClient(cc grpc.ClientConnInterface) FinanceServiceClient {
	return &financeServiceClient{cc}
}

func (c *financeServiceClient) Create(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/finance.FinanceService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetRecordsForDay(ctx context.Context, in *DateRequest, opts ...grpc.CallOption) (*Records, error) {
	out := new(Records)
	err := c.cc.Invoke(ctx, "/finance.FinanceService/GetRecordsForDay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) ProfitForMonth(ctx context.Context, in *DateRequest, opts ...grpc.CallOption) (*Profit, error) {
	out := new(Profit)
	err := c.cc.Invoke(ctx, "/finance.FinanceService/ProfitForMonth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetValuesForMonth(ctx context.Context, in *DateRequest, opts ...grpc.CallOption) (*Values, error) {
	out := new(Values)
	err := c.cc.Invoke(ctx, "/finance.FinanceService/GetValuesForMonth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financeServiceClient) GetValuesForYear(ctx context.Context, in *DateRequest, opts ...grpc.CallOption) (*Values, error) {
	out := new(Values)
	err := c.cc.Invoke(ctx, "/finance.FinanceService/GetValuesForYear", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinanceServiceServer is the server API for FinanceService service.
// All implementations should embed UnimplementedFinanceServiceServer
// for forward compatibility
type FinanceServiceServer interface {
	Create(context.Context, *Record) (*Empty, error)
	GetRecordsForDay(context.Context, *DateRequest) (*Records, error)
	ProfitForMonth(context.Context, *DateRequest) (*Profit, error)
	GetValuesForMonth(context.Context, *DateRequest) (*Values, error)
	GetValuesForYear(context.Context, *DateRequest) (*Values, error)
}

// UnimplementedFinanceServiceServer should be embedded to have forward compatible implementations.
type UnimplementedFinanceServiceServer struct {
}

func (UnimplementedFinanceServiceServer) Create(context.Context, *Record) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedFinanceServiceServer) GetRecordsForDay(context.Context, *DateRequest) (*Records, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecordsForDay not implemented")
}
func (UnimplementedFinanceServiceServer) ProfitForMonth(context.Context, *DateRequest) (*Profit, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProfitForMonth not implemented")
}
func (UnimplementedFinanceServiceServer) GetValuesForMonth(context.Context, *DateRequest) (*Values, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValuesForMonth not implemented")
}
func (UnimplementedFinanceServiceServer) GetValuesForYear(context.Context, *DateRequest) (*Values, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValuesForYear not implemented")
}

// UnsafeFinanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinanceServiceServer will
// result in compilation errors.
type UnsafeFinanceServiceServer interface {
	mustEmbedUnimplementedFinanceServiceServer()
}

func RegisterFinanceServiceServer(s grpc.ServiceRegistrar, srv FinanceServiceServer) {
	s.RegisterService(&FinanceService_ServiceDesc, srv)
}

func _FinanceService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance.FinanceService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).Create(ctx, req.(*Record))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetRecordsForDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetRecordsForDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance.FinanceService/GetRecordsForDay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetRecordsForDay(ctx, req.(*DateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_ProfitForMonth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).ProfitForMonth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance.FinanceService/ProfitForMonth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).ProfitForMonth(ctx, req.(*DateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetValuesForMonth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetValuesForMonth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance.FinanceService/GetValuesForMonth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetValuesForMonth(ctx, req.(*DateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinanceService_GetValuesForYear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServiceServer).GetValuesForYear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finance.FinanceService/GetValuesForYear",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServiceServer).GetValuesForYear(ctx, req.(*DateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FinanceService_ServiceDesc is the grpc.ServiceDesc for FinanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finance.FinanceService",
	HandlerType: (*FinanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _FinanceService_Create_Handler,
		},
		{
			MethodName: "GetRecordsForDay",
			Handler:    _FinanceService_GetRecordsForDay_Handler,
		},
		{
			MethodName: "ProfitForMonth",
			Handler:    _FinanceService_ProfitForMonth_Handler,
		},
		{
			MethodName: "GetValuesForMonth",
			Handler:    _FinanceService_GetValuesForMonth_Handler,
		},
		{
			MethodName: "GetValuesForYear",
			Handler:    _FinanceService_GetValuesForYear_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finance/pkg/proto/finance/finance.proto",
}
